name       : libdex
version    : 0.2.0
release    : 1
source     :
    - https://download.gnome.org/sources/libdex/0.2/libdex-0.2.0.tar.xz : a0f7566260971a1e4aeb53a07d95c806091257b8789d6fad9931dba872c5070d
license    : LGPL-2.1
component  : programming.library
summary    : A library supporting Deferred Execution
description: |
    A library supporting Deferred Execution
builddeps  :
    - pkgconfig(sysprof-capture-4)
    - gi-docgen
    - vala
patterns   :
    - docs :
      - /usr/share/doc/libdex-1
setup      : |
    %meson_configure -Dsysprof=true -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
